---
- hosts: all
  become: yes

  pre_tasks:
    - name: Force use of ansible.cfg to execute a playbook on a remote server
      lineinfile:
        path: /home/vagrant/.bashrc
        regexp: "^export ANSIBLE_CONFIG"
        line: "export ANSIBLE_CONFIG=/scientists/ansible/ansible.cfg"

    - name: Follow to project directory
      lineinfile:
        path: /home/vagrant/.bashrc
        regexp: "^cd /scientists"
        line: "cd /scientists"

  roles:
    - basic
    - ntp

- hosts: all
  become: yes
  become_user: postgres
  roles:
    - postgresql